# Script-mode regression check: no configure, compiler, build or firmware output.
cmake_minimum_required(VERSION 3.16)
set(ENV{IDF_PATH} [=[C:\Users\mati\esp\v5.4.1\esp-idf]=])
function(idf_component_register)
    cmake_parse_arguments(CHECK "" "" "SRCS;INCLUDE_DIRS;PRIV_INCLUDE_DIRS;REQUIRES" ${ARGN})
    if(NOT "hs_crack_crypto.c" IN_LIST CHECK_SRCS)
        message(FATAL_ERROR "Crypto source is not registered")
    endif()
    set(ANALYZER_SOURCES ${CHECK_SRCS})
    list(FILTER ANALYZER_SOURCES INCLUDE REGEX "^hs_capture_analyzer\\.c$")
    list(LENGTH ANALYZER_SOURCES ANALYZER_SOURCE_COUNT)
    if(NOT ANALYZER_SOURCE_COUNT EQUAL 1)
        message(FATAL_ERROR "Capture analyzer source must be registered exactly once")
    endif()
    set(SESSION_SOURCES ${CHECK_SRCS})
    list(FILTER SESSION_SOURCES INCLUDE REGEX "^hs_crack_session\\.c$")
    list(LENGTH SESSION_SOURCES SESSION_SOURCE_COUNT)
    if(NOT SESSION_SOURCE_COUNT EQUAL 1)
        message(FATAL_ERROR "Session store source must be registered exactly once")
    endif()
    set(HISTORY_SOURCES ${CHECK_SRCS})
    list(FILTER HISTORY_SOURCES INCLUDE REGEX "^hs_audit_history\\.c$")
    list(LENGTH HISTORY_SOURCES HISTORY_SOURCE_COUNT)
    if(NOT HISTORY_SOURCE_COUNT EQUAL 1)
        message(FATAL_ERROR "Audit history source must be registered exactly once")
    endif()
    set(ARTIFACT_SOURCES ${CHECK_SRCS})
    list(FILTER ARTIFACT_SOURCES INCLUDE REGEX "^hs_artifact_inventory\\.c$")
    list(LENGTH ARTIFACT_SOURCES ARTIFACT_SOURCE_COUNT)
    if(NOT ARTIFACT_SOURCE_COUNT EQUAL 1)
        message(FATAL_ERROR "Artifact inventory source must be registered exactly once")
    endif()
    set(SCHEDULER_SOURCES ${CHECK_SRCS})
    list(FILTER SCHEDULER_SOURCES INCLUDE REGEX "^hs_crack_scheduler\\.c$")
    list(LENGTH SCHEDULER_SOURCES SCHEDULER_SOURCE_COUNT)
    if(NOT SCHEDULER_SOURCE_COUNT EQUAL 1)
        message(FATAL_ERROR "Scheduler source must be registered exactly once")
    endif()
    if(NOT CHECK_PRIV_INCLUDE_DIRS STREQUAL "C:/Users/mati/esp/v5.4.1/esp-idf/components/mbedtls/mbedtls/library")
        message(FATAL_ERROR "Windows IDF path was not normalized: ${CHECK_PRIV_INCLUDE_DIRS}")
    endif()
endfunction()
function(target_compile_definitions)
endfunction()
include("${CMAKE_CURRENT_LIST_DIR}/../main/CMakeLists.txt")

# Invalid captures must leave the task before any remote artifact is prepared
# or local/remote verification worker is started.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../main/main.c" MAIN_SOURCE)
string(FIND "${MAIN_SOURCE}" "#define JANOS_VERSION_REQUIRED \"1.7.5\"" JANOS_REQUIRED_VERSION)
string(FIND "${MAIN_SOURCE}" "hs_capture_report_t capture_report = hs_capture_analyze_pcap(" ANALYZE_CALL)
string(FIND "${MAIN_SOURCE}" "if (capture_report.state != HS_CAPTURE_READY" READY_GUARD)
string(FIND "${MAIN_SOURCE}" "remote_capture_ready = hs_crack_remote_write_capture(" REMOTE_PREPARE)
string(FIND "${MAIN_SOURCE}" "if (!hs_crack_ui.run && !hs_crack_workers_start(" WORKER_START)
if(JANOS_REQUIRED_VERSION LESS 0)
    message(FATAL_ERROR "Tab5 must require the current JanOS 1.7.5 development build")
endif()
if(ANALYZE_CALL LESS 0 OR READY_GUARD LESS ANALYZE_CALL OR
   REMOTE_PREPARE LESS READY_GUARD OR WORKER_START LESS READY_GUARD)
    message(FATAL_ERROR "Capture preflight must guard every worker preparation/start path")
endif()
message(STATUS "Windows IDF path, analyzer, session store, history, artifact inventory, crypto and scheduler registration checks passed (no build)")
